class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Navigation Tabs
      'tab_assets': 'Assets',
      'tab_market': 'Market',
      'tab_trade': 'Trade',
      'tab_discover': 'Discover',
      'tab_me': 'Me',

      // Dashboard
      'total_assets': 'Total Assets',
      'action_send': 'Send',
      'action_receive': 'Receive',
      'action_swap': 'Swap',
      'action_more_tools': 'More Tools',
      'assets_tab': 'Assets',
      'defi_tab': 'DeFi',
      'nft_tab': 'NFT',
      'search_token': 'Search token or contract address',
      'add_custom_token': 'Add Custom Token',
      'address_copied': 'Address copied to clipboard!',
      'my_wallets': 'My Wallets',
      'add_wallet': 'Add Wallet',
      'manage_wallets': 'Manage Wallets',
      'no_wallets': 'No wallets yet',
      'click_to_create': 'Click to create a new wallet',

      // Welcome Screen
      'welcome_title': 'Your Multi-chain Wallet, Safe & Easy',
      'welcome_headline': 'Your Multi-chain Wallet, Safe & Easy',
      'welcome_subtitle': 'Supporting mainstream chains, EVM compatible chains, and Layer2.',
      'welcome_subheadline': 'Supporting mainstream chains, EVM compatible chains, and Layer2.',
      'have_account': 'I have an account',
      'i_have_account': 'I have an account',
      'have_account_sub': 'Import Wallet, KeyPal, MultiSig Wallet',
      'no_account': 'No accounts',
      'no_accounts': 'No accounts',
      'no_account_sub': 'Create Now',
      'create_now': 'Create Now',

      // Terms of Service
      'read_agree': 'Read & agree with',
      'terms_of_service': 'Terms of Service',
      'must_agree_terms': 'Please read and agree to the Terms of Service',

      // Set Master Password
      'set_master_pwd': 'Set Master Password',
      'set_master_pwd_sub': 'Use one password to unlock all your wallets. You won\'t need to set a separate password for each wallet.',
      'set_pwd_label': 'Set Password',
      'pwd_hint': 'Enter 8-128 characters',
      'confirm_pwd_label': 'Confirm Password',
      'confirm_pwd_hint': 'Please confirm password',
      'pwd_strength_weak': 'Weak',
      'pwd_strength_fair': 'Fair',
      'pwd_strength_good': 'Good',
      'pwd_strength_strong': 'Strong',
      'btn_confirm': 'Confirm',
      'btn_next': 'Next Step',
      'btn_next_step': 'Next Step',

      // Select Network
      'select_network': 'Select A Network',
      'select_network_title': 'Select A Network',
      'hd_wallet': 'HD Wallet',
      'multisig_wallet': 'MultiSig Wallet',
      'hardware_wallet': 'Hardware wallet',
      'single_network': 'SingleNetwork',
      'search_network_hint': 'Search with network or token symbol',
      'create_wallet': 'Create Wallet',
      'import_wallet': 'Import Wallet',
      'btn_cancel': 'Cancel',

      // Create Wallet
      'create_network_wallet': 'Create {network}',
      'create_hd_wallet': 'Create HD Wallet',
      'set_wallet_name_tip': 'Please set a name for the wallet',
      'set_wallet_name_sub': 'Please set a name for the wallet',
      'wallet_name': 'Wallet Name',
      'enter_wallet_name_hint': 'Please input wallet name',
      'backup_tips_title': 'Backup Recovery Phrase',
      'backup_tips_sub': 'Please write down the following 12 recovery phrase words in order.',
      'verify_phrase_title': 'Verify Recovery Phrase',
      'verify_phrase_sub': 'Please select the words in correct order to verify your backup.',

      // Import Wallet
      'import_wallets_title': 'Import Wallets',
      'recovery_phrase': 'Recovery Phrase',
      'recovery_phrase_sub': 'Restore wallet through Recovery Phrase',
      'private_key': 'Private Key',
      'private_key_sub': 'Restore wallet through Private Key',
      'keystore': 'Keystore',
      'keystore_sub': 'Restore wallet through Keystore file',
      'sync_wallet': 'Sync Wallet',
      'sync_wallet_sub': "Sync other EVM network's wallet",
      'cold_wallet': 'Cold Wallet',
      'cold_wallet_sub': 'Import wallet offline and isolate from network',
      'watch_wallet': 'Watch Wallet',
      'watch_wallet_sub': 'Supports wallet addresses and EIP-4527, compatible with cold wallets.',

      'enter_phrase_hint': 'Enter 12 or 24 mnemonic words separated by space',
      'enter_pk_hint': 'Enter 64-character hex private key',
      'enter_keystore_hint': 'Paste Keystore JSON content',
      'keystore_password': 'Keystore Password',
      'enter_keystore_pwd_hint': 'Enter password to decrypt Keystore',
      'paste': 'Paste',
      'advanced_mode': 'Advanced mode',
      'derivation_path': 'Derivation Path',
      'custom_path': 'Custom Path',
      'enter_custom_path': 'e.g. m/44\'/60\'/0\'/0/0',
      'btn_import': 'Import Wallet',
      'btn_sync': 'Sync Now',

      // Watch Wallet Screen
      'watch_wallet_title': 'Import Watch Wallet',
      'watch_address_label': 'Wallet Address',
      'watch_address_hint': 'Enter or paste wallet address (0x...)',
      'watch_wallet_tip': 'Watch wallet only tracks balance and transactions. No private keys are stored on this device.',

      // Sync Wallet Screen
      'sync_wallet_title': 'Sync Wallet',
      'sync_wallet_desc': 'Select an existing EVM wallet to synchronize to {network}:',
      'no_evm_wallets': 'No existing EVM wallets found to sync.',

      // Cold Wallet Screen
      'cold_wallet_title': 'Cold Wallet Mode',
      'cold_wallet_desc': 'Use this device offline as a secure hardware vault. Transactions are signed via QR codes without internet access.',
      'setup_cold_wallet': 'Setup Cold Wallet',

      // Swap & Bridge
      'swap_title': 'Swap & Bridge',
      'swap_tab': 'Swap',
      'bridge_tab': 'Bridge',
      'from_label': 'From',
      'to_label': 'To (estimated)',
      'all': 'All',
      'transfer_out_hint': 'Transfer out',
      'receive_hint': 'Receive',
      'balance_prefix': 'Balance: ',
      'btn_enter_amount': 'Enter an Amount',
      'btn_swap_now': 'Swap Now',
      'btn_swapping': 'Swapping...',
      'slippage_tolerance': 'Slippage Tolerance',
      'rate': 'Rate',
      'min_received': 'Minimum Received',
      'route': 'Route',
      'last_record': 'Last Record',
      'no_tx_records': 'No transaction records',
      'swap_success': 'Swap Successful!',

      // Me Screen
      'me_title': 'Me',
      'genius_user': 'Genius User',
      'no_active_wallet': 'No active wallet',
      'connected_wallets_count': '{count} wallet(s) connected',
      'security_password': 'Security & Password',
      'security_sub': 'Master Password & Vault Settings',
      'language_setting': 'Language',
      'language_current': 'English',
      'about_app': 'About Genius Wallet',
      'app_version': 'Version 1.0.0',
      'select_language': 'Select Language',
      'lang_en': 'English',
      'lang_zh': '简体中文 (Simplified Chinese)',

      // Send & Receive
      'send_title': 'Send',
      'receive_title': 'Receive',
      'recipient_address': 'Recipient Address',
      'amount': 'Amount',
      'network_fee': 'Network Fee',
      'available_balance': 'Available Balance',

      // Identity Wallet
      'identity_wallet_title': 'Identity Wallet (HD)',
      'identity_wallet_desc': 'Manage multi-chain assets with one recovery phrase. Supports Polygon, BNB Chain, Ethereum, Base, Arbitrum, Optimism.',
      'select_chains_to_create': 'Select Chains to Generate',
      'all_chains': 'All Supported Chains',
      
      // MultiSig Wallet
      'multisig_wallet_title': 'Multi-signature Wallet',
      'multisig_create': 'Create MultiSig',
      'multisig_import': 'Import MultiSig',
      'multisig_name_hint': 'e.g. Treasury MultiSig',
      'multisig_threshold_label': 'Required Signatures Threshold',
      'multisig_owners_label': 'Member Addresses',
      'multisig_contract_address': 'MultiSig Contract Address',
      'multisig_contract_hint': 'Enter MultiSig contract address (0x...)',
      'add_member': 'Add Member Address',
      'btn_deploy_multisig': 'Create MultiSig Wallet',
      'btn_import_multisig': 'Import MultiSig Wallet',

      // Hardware Wallet
      'hardware_wallet_title': 'Hardware Wallet',
      'keypal_hardware': 'KeyPal Hardware Wallet',
      'keypal_desc': 'TokenPocket official security card & KeyPal hardware',
      'ledger_hardware': 'Ledger Hardware Wallet',
      'ledger_desc': 'Connect Ledger Nano X / Flex / Stax via Bluetooth',
      'onekey_hardware': 'OneKey Hardware Wallet',
      'onekey_desc': 'Connect OneKey Classic / Touch / Pro hardware',
      'qr_cold_hardware': 'QR Air-gapped Hardware',
      'qr_cold_desc': 'Air-gapped hardware cold wallet with QR interaction',
      'pair_hardware_now': 'Pair & Import Address',

      // Search & Discovery
      'search_hub_title': 'Search',
      'search_placeholder': 'Search tokens, DApps or enter URL',
      'search_all': 'All',
      'search_tokens': 'Tokens',
      'search_dapps': 'DApps',
      'search_networks': 'Networks',
      'recent_searches': 'Recent Searches',
      'clear_history': 'Clear',
      'trending_searches': 'Trending',
      'no_search_results': 'No matching results found',
      'open_dapp': 'Open',
      'dapp_details': 'DApp Details',

      // Scan QR
      'scan_title': 'Scan QR Code',
      'scan_guide': 'Place QR code within frame to scan',
      'scan_album': 'Album',
      'scan_my_code': 'My QR Code',
      'scan_simulate': 'Simulate Scan',
      'scan_flashlight': 'Flashlight',
      'scan_result_address': 'Recipient Address Detected',
      'scan_result_wc': 'WalletConnect Request',
      'scan_result_dapp': 'Web3 DApp Link',

      // More Tools
      'more_tools_title': 'More Tools',
      'batch_transfer': 'Batch Transfer',
      'batch_transfer_sub': 'Send tokens to multiple addresses at once',
      'approval_revoke': 'Approval & Revoke',
      'approval_revoke_sub': 'Check & revoke risky token allowances',
      'token_security': 'Token Security Check',
      'token_security_sub': 'Scan honeypot, mint & tax risks',
      'rpc_switcher': 'Node Speed & Switcher',
      'rpc_switcher_sub': 'Measure latency & switch fast RPC',
      'gas_tracker': 'Gas Price Radar',
      'gas_tracker_sub': 'Real-time EIP-1559 Base Fee tracker',
      'msg_signer': 'Message Sign & Verify',
      'msg_signer_sub': 'Sign EIP-191 message & verify signature',
      'security_audit': 'Security Health Check',
      'security_audit_sub': 'Comprehensive 100-point security audit',

      // Market Screen
      'market_watchlist': 'Watchlist',
      'market_hot': 'Hot',
      'market_gainers': 'Gainers',
      'market_losers': 'Losers',
      'market_new': 'New',
      'market_ecosystem': 'Ecosystem',
      'sort_name_vol': 'Name / 24h Vol',
      'sort_last_price': 'Last Price',
      'sort_24h_change': '24h Chg%',
      'global_market_cap': 'Market Cap',
      'global_24h_vol': '24h Vol',
      'btc_dominance': 'BTC Dom',
      'empty_watchlist_tip': 'No tokens in watchlist. Tap star on any token to add here.',
      'search_market_hint': 'Search crypto name or contract',
      'market_cap_stat': 'Market Cap',
      'high_24h': '24h High',
      'low_24h': '24h Low',
      'circulating_supply': 'Circulating Supply',
      'trade_now': 'Trade / Swap',

      // Dashboard & Token Management
      'add_token_title': 'Add / Manage Tokens',
      'popular_tokens': 'Popular Tokens',
      'custom_token': 'Custom Token',
      'token_contract_address': 'Token Contract Address',
      'token_symbol': 'Token Symbol',
      'token_decimals': 'Decimals',
      'add_token_btn': 'Add Token to Wallet',
      'token_added_success': 'Token added successfully',
      'hide_small_balances': 'Hide Small Balances (< \$1)',
      'sort_by_value': 'Sort by Balance',
      'all_assets': 'All Assets',
      'filter_assets': 'Filter Assets',
      'explore_defi': 'Explore Top DeFi Protocols',
      'explore_nft': 'Explore NFT Marketplaces',
      'token_details': 'Token Details',
      'view_in_explorer': 'View in Explorer',

      // Generic
      'copy': 'Copy',
      'copied': 'Copied to clipboard',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'error': 'Error',
      'success': 'Success',
      'confirm': 'Confirm',
      'next': 'Next',

      // Send & Receive Detail Localization
      'send_on_network': 'Send on {network}',
      'receive_on_network': 'Receive {network}',
      'receive_guide_tip': 'Only send {network} ({symbol}) and compatible tokens to this address.',
      'set_amount': 'Set Amount',
      'requested_amount': 'Requested: {amount} {symbol}',
      'paste_address': 'Paste',
      'transfer_amount': 'Transfer Amount',
      'available': 'Available',
      'slow_speed': 'Slow',
      'standard_speed': 'Standard',
      'fast_speed': 'Fast',
      'gas_fee_label': 'Miner / Gas Fee',
      'confirm_transfer': 'Confirm Transfer',
      'tx_broadcast_success': 'Transaction broadcasted successfully!',
      'err_recipient_empty': 'Please enter recipient address',
      'err_invalid_address': 'Please enter a valid EVM address (0x...)',
      'err_amount_invalid': 'Please enter a valid transfer amount',
      'err_insufficient_balance': 'Insufficient balance',
      'err_enter_password': 'Please enter password',
      'select_token': 'Select Token',
      'copy_address': 'Copy Address',
      'share_address': 'Share Address',
      'scan_for_address': 'Scan QR code for address',
      'address_copied_share': 'Address copied ready to share!',

      // Wallet Details Screen
      'wallet_details': 'Wallet Details',
      'wallet_alias': 'Wallet Name',
      'export_private_key': 'Export Private Key',
      'export_keystore': 'Export Keystore',
      'delete_wallet': 'Delete Wallet',
      'rename_wallet': 'Rename Wallet',
      'rename_success': 'Wallet renamed successfully',
      'delete_wallet_confirm': 'Are you sure you want to delete this wallet? Make sure you have backed up the private key or recovery phrase.',
      'wallet_deleted_success': 'Wallet deleted successfully',
      'security_warning_export': 'Warning: Never share your private key or recovery phrase with anyone!',
      'confirm_export': 'Verify Password to Export',
      'enter_master_pwd_hint': 'Enter master password',

      // Discover Hub
      'discover_title': 'Discover',
      'search_dapp_or_url': 'Search DApps or enter URL',
      'featured_dapps': 'Featured DApps',
      'category_all': 'All',
      'category_defi': 'DeFi',
      'category_nft': 'NFT & GameFi',
      'category_tools': 'Tools',
      'category_social': 'Social',
      'recent_dapps': 'Recently Visited',
      'dapp_launch_btn': 'Open DApp',
      'dapp_warning': 'You are about to access a 3rd party decentralized application. Please protect your assets and verify approvals.',
      'dapp_visit_notice': 'Opening {dapp} in Web3 browser...',

      // Me Screen & Address Book
      'address_book': 'Address Book',
      'address_book_sub': 'Manage frequent contact addresses',
      'add_contact': 'Add Contact',
      'contact_name': 'Contact Name',
      'contact_name_hint': 'e.g. Alice',
      'contact_address': 'Contact Address',
      'contact_address_hint': '0x...',
      'contact_network': 'Network',
      'no_contacts_yet': 'No saved contacts yet',
      'contact_added_success': 'Contact added successfully',
      'contact_deleted': 'Contact deleted',
      'send_to_contact': 'Transfer',
      'node_settings': 'Node Settings & Speed',
      'node_settings_sub': 'Select fastest RPC endpoint',
      'help_and_feedback': 'Help & Feedback',
      'help_and_feedback_sub': 'User guide, FAQ & support',
      'faq_title': 'Frequently Asked Questions',
      'faq_1_q': 'How to ensure my assets are safe?',
      'faq_1_a': 'Never share your seed phrase, private key, or keystore with anyone. Genius Wallet is non-custodial; your keys are stored locally and encrypted.',
      'faq_2_q': 'What is Transit Swap?',
      'faq_2_a': 'Transit Swap aggregates liquidity across top DEXs to provide the best exchange rates and lowest slippage with one click.',
      'contact_support': 'Customer Support',
      'official_community': 'Official Community',
      'terms_and_privacy': 'User Agreement & Privacy Policy',

      // Swap Updates
      'swap_swapped_success': 'Swapped {fromAmount} {fromToken} to {toAmount} {toToken}!',
      'rates_updated': 'Exchange rates updated',

      // Environment & On-Chain Keys
      'env_mode_title': 'Environment Settings',
      'env_mode_live': 'Polygon Mainnet (Live)',
      'env_mode_live_desc': 'Broadcasts real transactions to Polygon blockchain (Requires Gas)',
      'env_mode_simulation': 'Simulation Mode (Sandbox)',
      'env_mode_simulation_desc': 'Local simulation mode for testing without gas',
      'env_badge_live': 'LIVE MAINNET',
      'env_badge_sim': 'SIMULATION',
      'tx_hash_label': 'Transaction Hash (TxHash)',
      'view_on_explorer': 'View on PolygonScan',
      'copy_tx_hash': 'Copy TxHash',
      'copied_tx_hash': 'Transaction hash copied!',
      'tx_broadcast_failed': 'Transaction Broadcast Failed',
      'tx_broadcasting': 'Signing & Broadcasting to Polygon...',
      'tx_success_title': 'On-Chain Broadcast Successful',
      'tx_nonce_label': 'Nonce',
      'tx_gas_price_label': 'Gas Price',
    },
    'zh': {
      // Navigation Tabs
      'tab_assets': '资产',
      'tab_market': '行情',
      'tab_trade': '闪兑',
      'tab_discover': '发现',
      'tab_me': '我的',

      // Dashboard
      'total_assets': '总资产',
      'action_send': '转账',
      'action_receive': '收款',
      'action_swap': '闪兑',
      'action_more_tools': '更多工具',
      'assets_tab': '资产',
      'defi_tab': 'DeFi',
      'nft_tab': 'NFT',
      'search_token': '搜索代币名称或合约地址',
      'add_custom_token': '添加自定义代币',
      'address_copied': '地址已复制到剪贴板！',
      'my_wallets': '我的钱包',
      'add_wallet': '添加钱包',
      'manage_wallets': '钱包管理',
      'no_wallets': '暂无钱包',
      'click_to_create': '点击创建新钱包',

      // Welcome Screen
      'welcome_title': '您的多链钱包，安全便捷',
      'welcome_headline': '您的多链钱包，安全便捷',
      'welcome_subtitle': '支持主流公链、EVM 兼容链以及 Layer2 网络。',
      'welcome_subheadline': '支持主流公链、EVM 兼容链以及 Layer2 网络。',
      'have_account': '已有账户',
      'i_have_account': '已有账户',
      'have_account_sub': '导入钱包、KeyPal、多签钱包',
      'no_account': '没有账户',
      'no_accounts': '没有账户',
      'no_account_sub': '立即创建',
      'create_now': '立即创建',

      // Terms of Service
      'read_agree': '我已仔细阅读并同意',
      'terms_of_service': '服务条款',
      'must_agree_terms': '请先阅读并同意服务条款',

      // Set Master Password
      'set_master_pwd': '设置主密码',
      'set_master_pwd_sub': '设置一个密码解锁所有钱包，无需为每个钱包单独设置密码。',
      'set_pwd_label': '设置密码',
      'pwd_hint': '请输入 8-128 位字符',
      'confirm_pwd_label': '确认密码',
      'confirm_pwd_hint': '请再次输入密码',
      'pwd_strength_weak': '弱',
      'pwd_strength_fair': '一般',
      'pwd_strength_good': '良好',
      'pwd_strength_strong': '强',
      'btn_confirm': '确认',
      'btn_next': '下一步',
      'btn_next_step': '下一步',

      // Select Network
      'select_network': '选择网络',
      'select_network_title': '选择网络',
      'hd_wallet': '身份钱包 (HD)',
      'multisig_wallet': '多签钱包',
      'hardware_wallet': '硬件钱包',
      'single_network': '单网络钱包',
      'search_network_hint': '搜索网络或代币名称',
      'create_wallet': '创建钱包',
      'import_wallet': '导入钱包',
      'btn_cancel': '取消',

      // Create Wallet
      'create_network_wallet': '创建 {network}',
      'create_hd_wallet': '创建 HD 钱包',
      'set_wallet_name_tip': '请为您的钱包设置一个名称',
      'set_wallet_name_sub': '请为您的钱包设置一个名称',
      'wallet_name': '钱包名称',
      'enter_wallet_name_hint': '请输入钱包名称',
      'backup_tips_title': '备份助记词',
      'backup_tips_sub': '请按顺序抄写以下 12 个助记词并妥善保管。',
      'verify_phrase_title': '验证助记词',
      'verify_phrase_sub': '请按正确的顺序点击助记词以完成验证。',

      // Import Wallet
      'import_wallets_title': '导入钱包',
      'recovery_phrase': '助记词导入',
      'recovery_phrase_sub': '通过助记词恢复钱包',
      'private_key': '私钥导入',
      'private_key_sub': '通过明文私钥恢复钱包',
      'keystore': 'Keystore 导入',
      'keystore_sub': '通过 Keystore 文件内容恢复钱包',
      'sync_wallet': '同步钱包',
      'sync_wallet_sub': '同步已有的 EVM 链钱包到当前网络',
      'cold_wallet': '冷钱包',
      'cold_wallet_sub': '离线导入钱包，与网络完全物理隔离',
      'watch_wallet': '观察钱包',
      'watch_wallet_sub': '支持钱包地址和 EIP-4527，可配合冷钱包使用',

      'enter_phrase_hint': '请输入 12 或 24 个助记词，用空格分隔',
      'enter_pk_hint': '请输入 64 位 16 进制私钥',
      'enter_keystore_hint': '请粘贴 Keystore JSON 内容',
      'keystore_password': 'Keystore 密码',
      'enter_keystore_pwd_hint': '请输入解密 Keystore 的密码',
      'paste': '粘贴',
      'advanced_mode': '高级模式',
      'derivation_path': '派生路径',
      'custom_path': '自定义路径',
      'enter_custom_path': '例如 m/44\'/60\'/0\'/0/0',
      'btn_import': '立即导入',
      'btn_sync': '立即同步',

      // Watch Wallet Screen
      'watch_wallet_title': '导入观察钱包',
      'watch_address_label': '钱包地址',
      'watch_address_hint': '请输入或粘贴钱包地址 (0x...)',
      'watch_wallet_tip': '观察钱包仅用于跟踪资产余额与交易明细，本设备不会存储私钥。',

      // Sync Wallet Screen
      'sync_wallet_title': '同步钱包',
      'sync_wallet_desc': '选择已有的 EVM 钱包快速同步至 {network} 网络：',
      'no_evm_wallets': '未找到可同步的 EVM 钱包。',

      // Cold Wallet Screen
      'cold_wallet_title': '冷钱包模式',
      'cold_wallet_desc': '将此设备作为完全离线的冷钱包使用，通过扫描二维码完成签名通信，不连接互联网。',
      'setup_cold_wallet': '配置冷钱包',

      // Identity Wallet
      'identity_wallet_title': '身份钱包 (HD)',
      'identity_wallet_desc': '一套助记词管理全链资产，安全多链合一。支持 Polygon、BNB Chain、Ethereum、Base、Arbitrum、Optimism。',
      'select_chains_to_create': '选择要派生的多链网络',
      'all_chains': '全部支持的公链',
      
      // MultiSig Wallet
      'multisig_wallet_title': '多签钱包',
      'multisig_create': '创建多签钱包',
      'multisig_import': '导入多签钱包',
      'multisig_name_hint': '例如：国库金库多签钱包',
      'multisig_threshold_label': '所需签名门限 (M-of-N)',
      'multisig_owners_label': '成员签名地址列表',
      'multisig_contract_address': '多签合约地址',
      'multisig_contract_hint': '请输入多签合约地址 (0x...)',
      'add_member': '添加成员地址',
      'btn_deploy_multisig': '创建多签钱包',
      'btn_import_multisig': '导入多签钱包',

      // Hardware Wallet
      'hardware_wallet_title': '硬件钱包',
      'keypal_hardware': 'KeyPal 硬件钱包',
      'keypal_desc': 'TokenPocket 官方安全芯片与 KeyPal 硬件',
      'ledger_hardware': 'Ledger 硬件钱包',
      'ledger_desc': '通过蓝牙连接 Ledger Nano X / Flex / Stax',
      'onekey_hardware': 'OneKey 硬件钱包',
      'onekey_desc': '通过蓝牙连接 OneKey Classic / Touch / Pro',
      'qr_cold_hardware': '二维码离线冷端',
      'qr_cold_desc': '通过离线二维码交互签名冷钱包',
      'pair_hardware_now': '配对并导入硬件地址',

      // Swap & Bridge
      'swap_title': '闪兑与跨链',
      'swap_tab': '闪兑',
      'bridge_tab': '跨链',
      'from_label': '转出',
      'to_label': '转入 (预估)',
      'all': '全部',
      'transfer_out_hint': '转出金额',
      'receive_hint': '预估到账',
      'balance_prefix': '余额: ',
      'btn_enter_amount': '请输入兑换数量',
      'btn_swap_now': '立即兑换',
      'btn_swapping': '兑换处理中...',
      'slippage_tolerance': '滑点设置',
      'rate': '参考汇率',
      'min_received': '最少收到',
      'route': '兑换路由',
      'last_record': '最近记录',
      'no_tx_records': '暂无交易记录',
      'swap_success': '兑换成功！',

      // Me Screen
      'me_title': '我的',
      'genius_user': 'Genius 用户',
      'no_active_wallet': '暂无激活钱包',
      'connected_wallets_count': '已连接 {count} 个钱包',
      'security_password': '安全与密码',
      'security_sub': '主密码与安全金库设置',
      'language_setting': '多语言设置',
      'language_current': '简体中文',
      'about_app': '关于 Genius Wallet',
      'app_version': '版本 1.0.0',
      'select_language': '选择语言',
      'lang_en': 'English (英文)',
      'lang_zh': '简体中文',

      // Send & Receive
      'send_title': '转账',
      'receive_title': '收款',
      'recipient_address': '收款人地址',
      'amount': '转账金额',
      'network_fee': '网络矿工费',
      'available_balance': '可用余额',

      // Send & Receive Detail Localization
      'send_on_network': '在 {network} 网络转账',
      'receive_on_network': '接收 {network}',
      'receive_guide_tip': '请仅向该地址充入 {network} ({symbol}) 及兼容代币。',
      'set_amount': '设置金额',
      'requested_amount': '指定收款: {amount} {symbol}',
      'paste_address': '粘贴',
      'transfer_amount': '转账金额',
      'available': '可用余额',
      'slow_speed': '慢速',
      'standard_speed': '推荐',
      'fast_speed': '极速',
      'gas_fee_label': '网络矿工费',
      'confirm_transfer': '确认转账',
      'tx_broadcast_success': '交易已成功广播到区块链网络！',
      'err_recipient_empty': '请输入收款人地址',
      'err_invalid_address': '请输入有效的 0x 开头钱包地址',
      'err_amount_invalid': '请输入有效的转账数量',
      'err_insufficient_balance': '账户余额不足',
      'err_enter_password': '请输入密码',
      'select_token': '选择代币',
      'copy_address': '复制地址',
      'share_address': '分享地址',
      'scan_for_address': '扫描二维码获取地址',
      'address_copied_share': '收款地址已复制，可直接粘贴分享！',

      // Wallet Details Screen
      'wallet_details': '钱包详情',
      'wallet_alias': '钱包名称',
      'export_private_key': '导出私钥',
      'export_keystore': '导出 Keystore',
      'delete_wallet': '删除钱包',
      'rename_wallet': '修改钱包名称',
      'rename_success': '钱包名称修改成功',
      'delete_wallet_confirm': '确定要删除此钱包吗？请确保您已妥善备份私钥或助记词，否则资产将无法找回。',
      'wallet_deleted_success': '钱包已成功删除',
      'security_warning_export': '安全警告：请勿将私钥或助记词透露给任何人！',
      'confirm_export': '验证主密码以导出',
      'enter_master_pwd_hint': '请输入主密码',

      // Discover Hub
      'discover_title': '发现',
      'search_dapp_or_url': '搜索 DApp 或输入链接',
      'featured_dapps': '精选推荐',
      'category_all': '全部',
      'category_defi': 'DeFi',
      'category_nft': 'NFT 与链游',
      'category_tools': '实用工具',
      'category_social': '社交协议',
      'recent_dapps': '最近使用',
      'dapp_launch_btn': '进入应用',
      'dapp_warning': '您即将访问第三方去中心化应用，请注意资产安全并仔细核对授权内容。',
      'dapp_visit_notice': '正在 Web3 浏览器中打开 {dapp}...',

      // Me Screen & Address Book
      'address_book': '地址本',
      'address_book_sub': '管理常用联系人与收款地址',
      'add_contact': '添加联系人',
      'contact_name': '联系人名称',
      'contact_name_hint': '例如：Alice',
      'contact_address': '联系人地址',
      'contact_address_hint': '0x...',
      'contact_network': '所属网络',
      'no_contacts_yet': '暂无保存的联系人',
      'contact_added_success': '联系人添加成功',
      'contact_deleted': '联系人已删除',
      'send_to_contact': '转账',
      'node_settings': '节点测速与设置',
      'node_settings_sub': '实时测速并切换最佳 RPC 节点',
      'help_and_feedback': '帮助与反馈',
      'help_and_feedback_sub': '使用手册、常见问题与客服支持',
      'faq_title': '常见问题解答',
      'faq_1_q': '如何确保我的钱包资产安全？',
      'faq_1_a': '绝不要向任何人透露您的助记词、私钥或 Keystore 文件。Genius Wallet 是完全非托管去中心化钱包，私钥均经由主密码加密保存在本地安全芯片中。',
      'faq_2_q': '什么是 Transit 闪兑？',
      'faq_2_a': 'Transit Swap 聚合了各大主流去中心化交易所流动性，为您智能路由最优兑换汇率与最低滑点。',
      'contact_support': '联系在线客服',
      'official_community': '官方社群',
      'terms_and_privacy': '服务协议与隐私条款',

      // Swap Updates
      'swap_swapped_success': '成功将 {fromAmount} {fromToken} 闪兑为 {toAmount} {toToken}！',
      'rates_updated': '行情汇率已刷新',

      // Generic
      'copy': '复制',
      'copied': '已复制到剪贴板',
      'cancel': '取消',
      'save': '保存',
      'delete': '删除',
      'error': '错误',
      'success': '成功',
      'confirm': '确认',
      'next': '下一步',

      // Search & Discovery
      'search_hub_title': '搜索',
      'search_placeholder': '搜索代币、DApp 或输入 URL',
      'search_all': '全部',
      'search_tokens': '代币',
      'search_dapps': 'DApps',
      'search_networks': '网络',
      'recent_searches': '历史搜索',
      'clear_history': '清空',
      'trending_searches': '热门搜索',
      'no_search_results': '未找到相关结果',
      'open_dapp': '进入',
      'dapp_details': 'DApp 详情',

      // Scan QR
      'scan_title': '扫一扫',
      'scan_guide': '将二维码/条形码放入框内，即可自动扫描',
      'scan_album': '相册',
      'scan_my_code': '我的收款码',
      'scan_simulate': '模拟扫码',
      'scan_flashlight': '手电筒',
      'scan_result_address': '已识别收款地址',
      'scan_result_wc': 'WalletConnect 连接请求',
      'scan_result_dapp': '识别到 DApp 链接',

      // More Tools
      'more_tools_title': '更多工具',
      'batch_transfer': '批量转账',
      'batch_transfer_sub': '一键批量向多个地址分发代币',
      'approval_revoke': '授权检测与撤销',
      'approval_revoke_sub': '检测并一键撤销高危代币授权',
      'token_security': '代币安全检测',
      'token_security_sub': '智能检测蜜罐风险、买卖税与增发权限',
      'rpc_switcher': '节点测速与切换',
      'rpc_switcher_sub': '实时测速并一键切换超低延迟节点',
      'gas_tracker': 'Gas 价格雷达',
      'gas_tracker_sub': '实时 Base Fee 与推荐矿工费监控',
      'msg_signer': '签名与验签工具',
      'msg_signer_sub': 'EIP-191 消息签名与签名有效性校验',
      'security_audit': '钱包安全体检',
      'security_audit_sub': '钱包多维度安全体检与风险排查',

      // Market Screen
      'market_watchlist': '自选',
      'market_hot': '热榜',
      'market_gainers': '涨幅榜',
      'market_losers': '跌幅榜',
      'market_new': '新币榜',
      'market_ecosystem': '公链生态',
      'sort_name_vol': '名称 / 24h成交额',
      'sort_last_price': '最新价',
      'sort_24h_change': '24h涨跌幅',
      'global_market_cap': '总市值',
      'global_24h_vol': '24h成交额',
      'btc_dominance': 'BTC占比',
      'empty_watchlist_tip': '暂无自选代币，点击代币星标即可加入自选关注',
      'search_market_hint': '搜索币种名称或合约地址',
      'market_cap_stat': '流通市值',
      'high_24h': '24h最高',
      'low_24h': '24h最低',
      'circulating_supply': '流通总量',
      'trade_now': '去闪兑',

      // Dashboard & Token Management
      'add_token_title': '代币管理',
      'popular_tokens': '热门代币',
      'custom_token': '自定义代币',
      'token_contract_address': '代币合约地址',
      'token_symbol': '代币符号',
      'token_decimals': '精度',
      'add_token_btn': '添加代币至钱包',
      'token_added_success': '代币添加成功',
      'hide_small_balances': '隐藏小额资产 (< \$1)',
      'sort_by_value': '按余额大小排序',
      'all_assets': '全部资产',
      'filter_assets': '资产筛选',
      'explore_defi': '探索主流 DeFi 协议',
      'explore_nft': '探索精选 NFT 市场',
      'token_details': '代币详情',
      'view_in_explorer': '区块浏览器',

      // Environment & On-Chain Keys
      'env_mode_title': '运行环境设置',
      'env_mode_live': 'Polygon 真实主网 (Live)',
      'env_mode_live_desc': '连接真实 Polygon 链上广播（需要真实 Gas）',
      'env_mode_simulation': '模拟测试模式 (Sandbox)',
      'env_mode_simulation_desc': '本地模拟模式（无须消耗真实 Gas，适合测试）',
      'env_badge_live': '主网实时',
      'env_badge_sim': '模拟测试',
      'tx_hash_label': '链上交易哈希 (TxHash)',
      'view_on_explorer': '在 PolygonScan 上查看',
      'copy_tx_hash': '复制交易哈希',
      'copied_tx_hash': '交易哈希已复制到剪贴板！',
      'tx_broadcast_failed': '链上交易广播失败',
      'tx_broadcasting': '正在签名并广播至 Polygon 主网...',
      'tx_success_title': '链上交易广播成功',
      'tx_nonce_label': 'Nonce',
      'tx_gas_price_label': 'Gas 费率',
    },
  };

  static String get(String key, String langCode, {Map<String, String>? params}) {
    final lang = _localizedValues.containsKey(langCode) ? langCode : 'en';
    String text = _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
    if (params != null) {
      params.forEach((paramKey, paramValue) {
        text = text.replaceAll('{$paramKey}', paramValue);
      });
    }
    return text;
  }
}
